# ScotPHO indicators: 2 indicators showing 5 year Period Life Expectancy for each SIMD quintile & whole of Scotland

# Female life Expectancy (inequality tab indicator)
# Male life expectancy (inequality tab indicator)

# Output from this script will only be visible within inequalities module of ScotPHO profiles tool
# The Scotland overall life expectancy may not match life expectancy indicators in main porfiles tool because they cover different time periods 
# (main profile indicator 3 year figure, inequalities 5 year figure)

# Life expectancy data generated by NRS - raw data behind the scotpho indicators is either downloaded from NRS website or a bespoke request
# sent to NRS.

# Inequalities measures for life expectancy require life expectancy data by SIMD quintile (generated by NRS) using equivalent time periods (eg 5 year average)
# Robust life expectancy estimate generation require sufficient data by individual year ages and sex and SIMD quintile this requires 5 years of data rather 
# than single year or 3 years data that is used in the main life expectancy profiles indicators

# Geographies available Scotland (Scotland Quintile), Council Area (using within Council SIMD quintile) and Health Board (within HB SIMD quinilte) 
# Within Scotland SIMD quintile estimates not available at CA or HB level as NRS do no routinely generate this data and unsure if the life expectancy would be 
# robust given likely many categories where cells would be small/zeros

#   Part 1 - Function for formatting data into required shape.
#   Part 1 - Import & manipulate raw data files provided by NRS.
#   Part 2 - Run analysis functions 

###############################################.
## Packages/Filepaths/Functions ----
###############################################.

source("1.indicator_analysis.R") #Normal indicator functions
source("2.deprivation_analysis.R") # deprivation function

# Extracts for Life Expectancy data saved in left expectancy network folder.
if (sessionInfo()$platform %in% c("x86_64-redhat-linux-gnu (64-bit)", "x86_64-pc-linux-gnu (64-bit)")) {
  source_network <- "/PHI_conf/ScotPHO/Life Expectancy/Data/Source Data/NRS data/"
} else {
  source_network <- "//stats/ScotPHO/Life Expectancy/Data/Source Data/NRS data/"
}

#################################################################.
#   Part 1 Function formatting into indicator output files ----
#################################################################.

save_output<-function(filename, ind_id) {
  
   data_depr <- data_depr %>%
    select(year, code, quintile, quint_type, denominator, rate, lowci,upci,sii:rel_range,trend_axis) %>% #select only required fields
    mutate(ind_id=ind_id, #populate ind_id with parameter supplied
           numerator = 0, #life expectancy has no numerator
           def_period = paste0(trend_axis,"; ","5 year period life expectancy"), #label period as 5 year
           quint_type=case_when(code=="S00000001" ~ "sc_quin", TRUE ~ quint_type)) %>% #set quintile type
    # fill in missing values and if any have negative lower CI change that to zero.
    mutate_at(c("rate", "lowci", "upci"), ~replace(., is.na(.), 0)) 

  data_depr$lowci <- ifelse(data_depr$lowci<0, 0, data_depr$lowci)
  
  #Preparing data for Shiny tool
  data_shiny <- data_depr %>% 
    select(-c(most_rate, least_rate, par_rr, count))
  
  #Saving file
  saveRDS(data_shiny, file = paste0(data_folder, "Data to be checked/", filename,"_ineq.rds"))
}


###############################################.
#   Part 1 - Import & manipulate raw data files provided by NRS. ----
###############################################.

# Open Health Board LE data
hb_depr_data <- read_excel(paste0(source_network,"life expectancy in Health boards split by SIMD 2001-2005 to 2017-2021.xlsx")) %>%
  setNames(tolower(names(.))) %>%  #variables to lower case
  mutate(quint_type=case_when(substr(area,1,4) != "Scot" ~ "hb_quin",substr(area,1,4) == "Scot" ~"sc_quin")) #add field labeling quintile type - within HB quintile

# Open Health Board LE data (remove Scotland level data as already avialable in HB level data extract)
ca_depr_data <- read_excel(paste0(source_network,"life expectancy in Council areas split by SIMD 2001-2005 to 2017-2021.xlsx")) %>%
  setNames(tolower(names(.))) %>% #variables to lower case
  mutate(quint_type="ca_quin")

# Bind HB and CA data & rename fields
data_depr <- bind_rows(hb_depr_data,ca_depr_data) %>%
  filter(age_band=="less than 1") %>%
  rename(lowci= lower_le, upci=upper_le,rate=ex, denominator=populations, trend_axis=period) %>%
  mutate(quintile = substr(area, nchar(area)-1+1, nchar(area)),
         quintile = case_when(quintile=="0" ~ "Total", TRUE ~ quintile),
         area=substr(area,start=1,stop = nchar(area)-1),
         year=as.numeric(substr(trend_axis,1,4))+2) %>% #year field set to mid-point of time series - used in charting
  select(-lx,-age_band, -deaths)

# adjust scotland area code to match scotpho standard
data_depr_all <-data_depr %>%
  mutate(code= case_when(areacode == "S92000003" ~ "S00000001",TRUE ~ areacode)) %>%
  select (-areacode)

rm(hb_depr_data,ca_depr_data)


##################################################.
##  Part 2 - Call deprivation analysis functions ----
##################################################.
##Female Life expectancy 
data_depr <- data_depr_all %>%
  filter(sex == "F") %>% 
  #call function from "2.deprivation_analysis" script which generate measures of inequality (sii/rii/paf)
  inequality_measures()

save_output(filename="life_expectancy_female", ind_id=20102)

##################################################.
##Male Life expectancy 
data_depr <- data_depr_all %>%
  filter(sex == "M") %>% 
  #call function from "2.deprivation_analysis" script which generate measures of inequality (sii/rii/paf)
  inequality_measures()

#call function to save file
save_output(filename="life_expectancy_male", ind_id=20101)

##################################################.
##  Part 3 - Checking charts ----
# just some quick charts checking how measure data is looking as usual checking scripts aren't run
# Use the plot output window to make sure tredns and patterns look as expected (at least at the scotland level) 
##################################################. 
 
####Charting rate by quintile ----
 
chart <- data_depr %>%
filter(code=="S00000001" & quintile !="Total")

 p <- plot_ly(data=chart , x=~trend_axis) %>%
   #Comparator line
   add_lines(y = ~rate, name = "Life Ex", type = 'scatter', mode = 'lines',
             color=~quintile, text= ~quintile, hoverinfo="text") %>%
   layout(bargap = 0.1, margin=list(b = 140), #to avoid labels getting cut out
          showlegend = FALSE) %>%
   config(displayModeBar = F, displaylogo = F, editable =F) # taking out toolbar

 p
 

####Charting sii ----

chart2 <- data_depr %>%
  filter(code=="S00000001" & quintile =="Total")

sii_plot <- plot_ly(data=chart2, x=~trend_axis,hoverinfo="text") %>%
  add_lines(y = ~sii, name = "Absolute inequality (SII)", type = 'scatter', mode = 'lines',
            line = list(color = '#74add1'))  %>% 
  #Layout
  layout(showlegend = FALSE,
         margin = list(b = 140)) %>% 
  config(displayModeBar = FALSE, displaylogo = F,  editable =F) # taking out toolbar

sii_plot

####Charting rii ----

rii_plot <- plot_ly(data=chart2, x=~trend_axis)%>%
  add_lines(y = ~rii,name = "Relative gap", type = 'scatter', mode = 'lines',
            line = list(color = '#313695')) %>% 
  #Layout
  layout(showlegend = FALSE, margin = list(b = 140))%>%
  config(displayModeBar = FALSE, displaylogo = F, editable =F) # taking out toolbar

rii_plot

####Charting paf ----

#preparing data needed, creates two dummy variables for stacked bar chart
chart3<- data_depr %>%
  filter(code=="S00000001" & year=="2018" & quintile !="Total") %>%
  mutate(baseline = rate[quintile == "5"],
         diff_baseline = rate - rate[quintile == "5"]) %>% 
  droplevels()

par_bar_plot <- plot_ly(data = chart3, x = ~quintile, 
                        textposition="none", hoverinfo="text") %>%
  add_bars(y = ~baseline, name= "", marker = list(color = "#4da6ff"), showlegend = FALSE) %>%   
  add_bars(y = ~diff_baseline, name = "Attributable to deprivation", 
           marker = list(color = "#ffa64d"), showlegend = FALSE) %>% 
  layout(bargap = 0.1, barmode = 'stack', showlegend = T, 
         legend = list(x = 0.9, y = 0.9),
         margin = list(b = 140)) %>% #to avoid labels getting cut out
  config(displayModeBar = FALSE, displaylogo = F, editable =F) # taking out toolbar

par_bar_plot 


#END