# Child protection with parental drug or alcohol misuse.R

# 3 indicators generated by this script:
# Child protection with parental drug misuse
# Child protection with parental alcohol misuse
# Child protection with parental drug or alcohol misuse

# Full definition:
# Rate of Child Protection Case Conference where parental drug, alcohol or substance misuse (ie drug &/or alcohol)
# has been identified for children on the register at 31st July, per 10,000 population aged under 18.

#   Part 1 - Read in data downloaded from SG and format for functions
#   Part 2 - Run analysis functions 
#   Part 2 - Run analysis functions 


###############################################################################. 
## Analyst Notes on generating this indicator data ----

# This script analyses Scottish Government data on the number of children protection parental alcohol, drugs, substance misuse by a local authority 

## Data are downloaded from the childrens social work publication on SG website:
## https://www.gov.scot/publications/childrens-social-work-statistics-scotland-2020-21/documents/
## See Excel files: Children's Social Work Statistics 2020-21 Additional Tables
## Table 4.6

# Figures are published for Scotland and local authorities only. (ScotPHO derive NHS board figures by aggregating council area figures)

# Each year (around March) the SG publish an additional year of data.
# The ScotPHO indicator raw dataset is generated by manually copying newly published data from the SG publication and adding this to historic indicator raw data excel file saved
# "\\Isdsf00d03\ScotPHO\Profiles\Data\Received Data\child_protection_with_parental_drug_or_alcohol_misuse_2012to2021.xlsx"
# Upadte filename suffix when adding new year of data.

# !!! IMPORTANT ANALYST NOTE: SG apply suppression to published data meaning it is not possible to calculate the Scotland total from the sum of local authorities
# ScotPHO indicator functions scripts usually rely on aggregating up smaller units of geographies
# to ensure the function script generates the correct Scotland total insert a row for each year that has no label for the local authority but contains
# the number necessary to ensure the sum of the annual data sums to the correct Scotland total (calcuate this by summing local authority total and subtracting from published scotland total). 
# analysis function script will incorporate these numbers into Scotland total but ignores the 'na' when it comes to generating council level data

# Suppression of source data complicates indicator production process.
# ScotPHO need to also apply suppression to the data we load into shiny app so that we can accurately display true zeros (and not confused blanks causes by presence of * or NAs in source data) 


# HISTORIC DATA REVISIONS : In March 2022 revised figures for the previous year (2020) were released for some geographies
# Glasgow (drug & substance misuse), North Ayrshire all 3, South Lanarkshire all 3, West Dunbartonshire (alcohol & substance misuse) 

###############################################################################.

###############################################.
## Packages/Filepaths/Functions ----
###############################################.

source("./1.indicator_analysis.R") #Normal indicator functions
library("stringr")#for string_replace() function


################################################################################. 
## Part 1 - Read in data downloaded from SG and format for functions ----
################################################################################.

# open a lookup that will add la standard geography codes to the la names present in social work dataset
ca <- readRDS(paste0(lookups,"Geography/CAdictionary.rds")) %>%
  rename("ca"="code")

# read in excel - (note for 2022 update the 2020 data was overwritten with revised estimates and new 2021 data added)
# remember that SG apply suppression to data they provide to scotpho.
# profiles data is generated by summing values of smallest unit of geography up - without manual intervention this will cause errors for this particular indicator
# To ensure accurate aggregation to scotland total there are some rows manually created by scotpho analyst in the source excel which contain figures that will ensure scotland total is correct  
# Manually check what the total for all LA figures is and compare to scotland total figure from soruce data - then insert a dummy row (where LA= NA) but includes the number that would be required to make LA totals add up to true scottish total
# Rows with LA = NA will not appear as a row in final dataset but do contribute to scottish total.

df_received<-read_excel("/PHI_conf/ScotPHO/Profiles/Data/Received Data/CP CSWS 2012_21 revised 19_20.xlsx") %>%
  mutate(la = str_replace(la, "Glasgow","Glasgow City"),
         la = str_replace(la, "Edinburgh, City of","City of Edinburgh"),
         la = str_replace(la, "Eilean Siar","Na h-Eileanan Siar"),
         la = str_replace(la, "&","and"),
         across(contains(c("drug", "alcohol", "substance_misuse")), as.numeric)) %>% #convert data columns to numeric (suppressed)
    left_join(ca, by = c("la" = "areaname"), all.x = TRUE) # join with council area lookup

#open 'geo_check_recieved dataframe and check that all la that have a 9 digit standard geo code have been matched
#there will be rows for 'na' but should be no rows where names of councils don't match to a geography code
geo_check_recieved <- df_received %>%
  group_by(la, ca) %>%
  summarise(count=n())

rm(ca)
rm(geo_check_recieved)

# prepare child protection with parental drug use - file to pass to analysis functions
parental_drug <- df_received %>% select(c(year,ca, drug)) %>% 
  rename("numerator"="drug")
saveRDS(parental_drug, file=paste0(data_folder, "Prepared Data/child_protection_parental_drug_raw.rds")) 

# prepare child protection with parental drug use
parental_alcohol <- df_received %>% select(c(year,ca, alcohol)) %>% 
  rename("numerator"="alcohol") 
saveRDS(parental_alcohol, file=paste0(data_folder, "Prepared Data/child_protection_parental_alcohol_raw.rds")) 

# prepare child protection with substance misuse
parental_substance <- df_received %>% select(c(year,ca, substance_misuse)) %>% 
  rename("numerator"="substance_misuse") 
saveRDS(parental_substance, file=paste0(data_folder, "Prepared Data/child_protection_parental_substance_misuse_raw.rds")) 


################################################################################.
## Part 2 - Suppressions  ---- 
################################################################################. 
# This part is required to ensure that any geography that has been suppressed in the raw data (or any unit of geography that is built up from suppressed data)
# is still suppressed in the file fed into the shiny profiles app

# geo lookup required to which tell which LA are subunits of which NHS boards
geo_lookup <- readRDS(paste0(lookups, "Geography/DataZone11_All_Geographies_Lookup.rds")) %>%
  group_by(ca2019,hb2019,adp) %>%
  summarise(count=n()) %>%
  ungroup() %>%
  select(-count)

# flag numerator cells from child protection raw dataset have suppression applied
cp_suppressions <- df_received %>% 
  mutate(drug_suppressed=case_when(is.na(drug) ~ "*",TRUE ~""),
         alcohol_suppressed=case_when(is.na(alcohol) ~ "*",TRUE ~""),
         substance_suppressed=case_when(is.na(substance_misuse) ~ "*",TRUE ~"")) %>%
  rename (ca2019=ca) %>% #rename to ease join with geo lookup 
  filter(!is.na(ca2019)) %>% #remove any NA council areas (ie dummy rows to ensure scotland total correct)
  select(-la)

#match file detailing which years and areas have suppression to geo lookup so we can tell which parent NHS boards should also be suppressed
cp_suppressions <- left_join(cp_suppressions,geo_lookup,by = "ca2019")

#manipulate df to give one row per geographic code and year
cp_suppressions <-cp_suppressions %>%
  pivot_longer(cols = c("ca2019","hb2019","adp"),values_to = "code") %>%
  group_by(year,code,drug_suppressed,alcohol_suppressed,substance_suppressed) %>%
  summarise(count=n()) %>%
  ungroup()

#flagging year and geography when suppression applied to drugs
cp_drug_suppresion <-cp_suppressions %>%
  filter(drug_suppressed=="*") %>%
  select( year, code, drug_suppressed)

#file flagging year and geography when suppression applied to alcohol
cp_alcohol_suppresion <-cp_suppressions %>%
  filter(alcohol_suppressed=="*") %>%
  select( year, code, alcohol_suppressed)

#file flagging year and geography when suppression applied to substance misuse
cp_substance_suppresion <-cp_suppressions %>%
  filter(substance_suppressed=="*") %>%
  select( year, code, substance_suppressed)

rm(geo_lookup)

################################################################################.
## Part 3 - Run analysis functions for 3 indicators---- 
################################################################################. 

################################################################################. 
## Child protection with parental drug use

analyze_first(filename = "child_protection_parental_drug", geography = "council",               
              measure = "crude", yearstart = 2012, yearend = 2021, 
              time_agg = 1, pop = "CA_pop_under18", adp = TRUE) 

analyze_second(filename = "child_protection_parental_drug", measure = "crude", time_agg = 1,               
               ind_id = 4130, year_type = "July snapshot", crude_rate = 10000)

## overwrite data output from functions with correct suppression applied
filename <- "child_protection_parental_drug"
pre_suppression_data <- readRDS(file=paste0(data_folder, "Data to be checked/", filename, "_shiny.rds"))

drug_final_result <- left_join(pre_suppression_data, cp_drug_suppresion, by=c("code", "year"))

drug_final_result <- drug_final_result %>%
  mutate(numerator=case_when(is.na(drug_suppressed) ~ numerator),
         rate=case_when(is.na(drug_suppressed) ~ rate),
         lowci=case_when(is.na(drug_suppressed) ~ lowci),
         upci=case_when(is.na(drug_suppressed) ~ upci)) %>%
  select (-drug_suppressed)

# Including both rds and csv file for now
saveRDS(drug_final_result, file = paste0(data_folder, "Data to be checked/", filename, "_shiny.rds"))
write_csv(drug_final_result, path = paste0(data_folder, "Data to be checked/", filename, "_shiny.csv"))


################################################################################. 
## Child protection with parental alcohol use

analyze_first(filename = "child_protection_parental_alcohol", geography = "council",               
              measure = "crude", yearstart = 2012, yearend = 2021, 
              time_agg = 1, pop = "CA_pop_under18", adp = TRUE) 

analyze_second(filename = "child_protection_parental_alcohol", measure = "crude", time_agg = 1,               
               ind_id = 4110, year_type = "July snapshot", crude_rate = 10000)


################################################################################. 
## Child protection with parental substance  misuse
analyze_first(filename = "child_protection_parental_substance_misuse", geography = "council",               
              measure = "crude", yearstart = 2012, yearend = 2021, 
              time_agg = 1, pop = "CA_pop_under18", adp = TRUE) 

analyze_second(filename = "child_protection_parental_substance_misuse", measure = "crude", time_agg = 1,               
               ind_id = 4153, year_type = "July snapshot", crude_rate = 10000)


###END ----

