# Child protection with parental drug or alcohol misuse.R

# 5 indicators generated by this script:
# 1. Child protection with parental drug misuse (ind_id = 4130)
# 2. Child protection with parental alcohol misuse (ind_id = 4110)
# 3. Child protection with parental drug or alcohol misuse (ind_id = 4153)
# 4. Children on the child protection register (ind_id = 13035)
# 5. Inter-agency referrals 

# Full definition: (indicators 1-3)
# Rate of Child Protection Case Conference where parental drug, alcohol or substance misuse (ie drug &/or alcohol)
# has been identified for children on the register at 31st July, per 10,000 population aged under 18.

# Full definition: (indicator 4)
# Children on the child protection register; number and rate per 1,000 children under 18 years.
# N.B. Prior to 2025 the definition used on the site was under 16 years, but the data used were 0-17 year olds (mistakenly I think). 
# The same numerators are being used from now, but the denominators used to calculate the rates will be larger (0-17 year olds rather than 0-15 year olds)
# so the rates may be slightly smaller than previously presented. 
# N.B.2 Children can be placed on the child protection register before birth. As we do not have population denominators for unborn children, 
# we need to note that any rates are per 1000 0-17 year old children.

# Full definition: (indicator 5) 
# Number of children aged 17 years or under per 1,000 subject to interagency referral discussions 
# (the first stage in formal child protection proceedings where young people may be at risk of harm or abuse)

###############################################################################. 
## Analyst Notes on generating this indicator data ----

# This script analyses Scottish Government data on the number of children protection parental alcohol, drugs, substance misuse by local authority 

## Data are downloaded from the childrens social work publication on SG website:
## https://www.gov.scot/collections/childrens-social-work/

# Figures are published for Scotland and local authorities only. (ScotPHO derive NHS board and ADP figures by aggregating council area figures)

# Each year (around March) the SG publish an additional year of data.

###############################################################################.

###############################################.
## Packages/Filepaths/Functions ----
###############################################.

### Load functions/dependencies ----

source("functions/main_analysis.R") # for packages and QA function 
source("functions/deprivation_analysis.R") # for packages and QA function
library(readxl) # imports xls and xlsx 

### Lookups ----

# Read in geography profiles_lookups
geo_lookup <- readRDS(paste0(profiles_lookups, "/Geography/opt_geo_lookup.rds")) %>% 
  select(!c(parent_area, areaname_full))


# Make a pop lookup (all need 0-17y, with age groups and sex splits for Scotland)
# Age groups in the data differ from usual age groups, hence why bespoke lookup needed.
popfile <- readRDS("/conf/linkage/output/lookups/Unicode/Populations/Estimates/CA2019_pop_est_1981_2023.rds") %>%
  filter(age<18) %>%
  mutate(agegp = case_when(age %in% c(0:4) ~ "0-4", # age groups in the data
                                 age %in% c(5:10) ~ "5-10",
                                 age %in% c(11:15) ~ "11-15",
                                 age %in% c(16:17) ~ "16-17")) %>%
  mutate(sex = case_when(sex_name == "M" ~ "Male",
                         sex_name == "F" ~ "Female")) %>%
  select(year, code = ca2019, agegp, sex, denominator = pop)
  
pop_la <- popfile %>%
  mutate(split_name = "Total", 
         split_value = "Total") %>%
  select(-agegp, -sex)

pop_scot <- popfile %>%
  mutate(code = "S00000001",
         split_name = "Total", 
         split_value = "Total") %>%
  select(-agegp, -sex)

pop_scot_sex <- popfile %>%
  mutate(code = "S00000001",
         split_name = "Sex", 
         split_value = sex) %>%
  select(-agegp, -sex)

pop_scot_agegp <- popfile %>%
  mutate(code = "S00000001",
         split_name = "Age group", 
         split_value = agegp) %>%
  select(-agegp, -sex)

pop_scot_sex_total <- pop_scot_sex %>%
  mutate(split_value = "All") 

pop_scot_agegp_total <- pop_scot_agegp %>%
  mutate(split_value = "Total") 

pop_lookup <- rbind(pop_la, 
                    pop_scot,
                    pop_scot_agegp, 
                    pop_scot_agegp_total,
                    pop_scot_sex,
                    pop_scot_sex_total) %>%
  group_by(year, code, split_name, split_value) %>%
  summarise(denominator = sum(denominator)) %>%
  ungroup()

# repeat 2023 data for 2024: (have added this to the caveats column)
# when indicator is updated in future the correct 2024 population should be applied and historic rates corrected
pop_lookup_incl_2024 <- pop_lookup %>%
  filter(year == 2023) %>%
  mutate(year = 2024) %>%
  rbind(pop_lookup)

# Make a CA_pop_under18 population lookup file with 2023 repeated to give 2024 data:
CA_pop_under18 <- readRDS(file=paste0(profiles_lookups, "/Population/CA_pop_under18.rds"))
CA_pop_under18_to2024 <- CA_pop_under18 %>% 
  filter(year==2023) %>% 
  mutate(year=2024) %>%
  rbind(CA_pop_under18)
# Save so main_analysis can use it
saveRDS(CA_pop_under18_to2024, file=paste0(profiles_lookups, "/Population/CA_pop_under18_to2024.rds"))


### Paths ----

# Identify data folder
chprot_data_folder <- paste0(profiles_data_folder, "/Received Data/SG CYP Social Work stats/")

# Identify data files 
publication_2023 <- "Child+Protection+Statistics+2023-24+Publication+Tables.xlsx"                             
additional_2023 <- "Child+Protection+Statistics+2023-24+Additional+Tables.xlsx"                              
additional_2022 <- "Children%27s+Social+Work+Statistics+-+Child+Protection+2022-23+-+Additional+Tables.xlsx" 
additional_2021 <- "Children%27s+Social+Work+Statistics+2021-22+-+Additional+Tables.xlsx"                
additional_2020 <- "childrens-social-work-statistics-2020-21-additional-tables.xlsx"                         
additional_2019 <- "childrens-social-work-statistics-2019-20-additional-tables.xlsx"                         
additional_2018 <- "childrens-social-work-statistics-2018-19-revised-additional-tables.xlsx"                 
additional_2017 <- "additional-tables_2017to2018.xlsx"                                                       
additional_2016 <- "CSWS-2016-17.xlsx"                                                                  
additional_2015 <- "CSWS+Additional+Tables+2015-16.xlsx"      
additional_2014 <- "CSWS-addtional-2014-15.xlsx"      
additional_2013 <- "CSWS-2013-14.xlsx"      
additional_2012 <- "CSWS-2012-13.xls"      
additional_2011 <- "CSWS-2011-12.xls"      

### Bespoke functions ----

# Function to import data from a wide format tab, and replace suppressed with NA
import_wide_data <- function(filename, sheetnum, range, non_num_cols) {
  df <- read_excel(paste0(chprot_data_folder, filename),
                   sheet = paste0("Table ", sheetnum),
                   range = range) %>%
    mutate(across(everything(), ~str_replace(., "\\*", "NA"))) %>%
    mutate(across(-all_of(non_num_cols), ~as.numeric(.)))  
}  


# Function to import LA data from a wide format tab, replace suppressed with NA, make long, and standardise var names
import_wide_LA_data <- function(filename, sheetnum, range, year) {
  df <- read_excel(paste0(chprot_data_folder, filename),
                   sheet = paste0("Table ", sheetnum),
                   range = range) %>%
    mutate(across(everything(), ~str_replace(., "\\*", "NA"))) %>%
    mutate(across(everything(), ~str_replace(., "-", "NA"))) %>%
    mutate(across(everything(), ~str_replace(., " and ", " & "))) %>%
    mutate(across(-1, ~as.numeric(.))) %>%
    pivot_longer(-(1), names_to = "indicator", values_to = "numerator") %>%
    mutate(year = as.numeric(year),
           areatype = "Council area") %>%
    rename(areaname = 1) %>%
    select(areaname, areatype, year, indicator, numerator)   
}  


################################################################################. 
## Part 1 - Read in data downloaded from SG and format for functions ----
################################################################################.


########################################################################################
# CHILD PROTECTION REGISTER DATA
########################################################################################

# Import the data: 

# Scotland (2013-2024) (snapshot as of 31 July)
register_2013to2024 <- import_wide_data(filename = publication_2023, sheetnum = "1.1", range = "A18:N39", non_num_cols = c(1:2)) %>%
  mutate(sex = ifelse(Category == "Total", as.character(NA), Category)) %>% 
  fill(sex) %>% # replaces Total with the relevant sex/all 
  rename(agegp = Subcategory) %>%
  select(-Category) %>%
  pivot_longer(-c(agegp, sex), names_to = "year", values_to = "numerator", names_transform = list(year = as.integer)) %>%
  select(year, sex, agegp, numerator) %>% 
  filter((sex %in% c("Male", "Female") & agegp=="Total") | sex=="All") %>%
  filter(agegp != "Unknown") %>%
  mutate(agegp = ifelse(agegp=="16+", "16-17", agegp))

# Scotland (2000-2012) (add metadata caveat re: change of snapshot date from 31 March in 2000-2010, to 31 July from 2011 onwards)
register_2000to2012 <- import_wide_data(filename = additional_2011, sheetnum = "2.1", range = "A13:N39", non_num_cols = 1) %>%
  mutate(sex = case_when(`2000`==1080 ~ "Male", #very clunky way of coding the data based on the data values!
                         `2000`==970 ~ "Female",
                         `2000`==2050 ~ "All"),
         agegp = case_when(`...1`=="Unborns(2)" ~ "Unborn",
                           `2000`==837 ~ "0-4",
                           `2000`==718 ~ "5-10",
                           `2000`==466 ~ "11-15",
                           `2000`==28 ~ "16-17",
                           !is.na(sex) ~ "Total"),
         sex = case_when(!is.na(agegp) & is.na(sex) ~ "All",
                         TRUE ~ sex)) %>%
  filter(!is.na(sex)) %>%
  select(-...1) %>%
  pivot_longer(-c(sex, agegp), names_to = "year", values_to = "numerator", names_transform = list(year = as.integer)) %>%
  select(year, sex, agegp, numerator) 

# Combine Scotland data and add split info
register_scot_sex <- rbind(register_2000to2012, register_2013to2024) %>%
  filter(sex %in% c("Male", "Female", "All") & agegp=="Total") %>%
  rename(split_value = sex) %>%
  mutate(split_name = "Sex") %>%
  select(-agegp)
  
register_scot_agegp <- rbind(register_2000to2012, register_2013to2024) %>%
  filter(agegp %in% c("0-4", "11-15", "16-17", "5-10", "Unborn", "Total") & sex=="All") %>%
  rename(split_value = agegp) %>%
  mutate(split_name = "Age group") %>%
  select(-sex)

register_scot <- rbind(register_scot_agegp, register_scot_sex) %>%
  mutate(code = "S00000001",
         ind_id = 13035,
         trend_axis = as.character(year),
         def_period = paste0(year, " - snapshot")) %>%
  merge(y=pop_lookup_incl_2024, by=c("year", "code", "split_name", "split_value")) %>% # unborn agegp dropped in this stage as no denominators
  calculate_crude_rate(., 1000) %>%
  select(-denominator)
  
# Save
write_rds(register_scot, paste0(profiles_data_folder, "/Data to be checked/child_prot_register_shiny_popgrp.rds"))
write.csv(register_scot, paste0(profiles_data_folder, "/Data to be checked/child_prot_register_shiny_popgrp.csv"), row.names = FALSE)

# QA popgrp data:
run_qa(type = "popgrp", filename = "child_prot_register", test_file=FALSE)



# LA (2013-2024)
register_la_2013to2024 <- import_wide_data(filename = publication_2023, sheetnum = "1.2", range = "A40:Y72", non_num_cols = c(1)) %>%
  pivot_longer(-`Local authority`, names_to = c("year", "metric"), 
               names_pattern = "(\\d{4}) (\\w*).*?", # (\\d{4}) extracts a 4-digit number, and (\\w*) extracts a word (either 'Rate' or 'Number') after a space after the number
               values_to = "value", names_transform = list(year = as.integer)) %>%
  pivot_wider(names_from = metric, values_from = value) %>%
  mutate(areatype = "Council area")  %>%
  select(areaname = `Local authority`, areatype, year, numerator = Number) %>%
  mutate(areaname = str_replace(areaname, " and "," & ")) %>%
  merge(y = geo_lookup, by=c("areaname", "areatype"), all.x=T)

# LA (2007-2012)
register_la_2007to2012 <- import_wide_data(filename = additional_2011, sheetnum = "2.2", range = "A5:M37", non_num_cols = c(1))
names(register_la_2007to2012) <- c("areaname", "2007", "rate", "2008", "rate", "2009", "rate", "2010", "rate", "2011", "rate", "2012", "rate")
register_la_2007to2012 <- register_la_2007to2012 %>%
  select(-rate) %>%
  pivot_longer(-areaname, names_to = "year", values_to = "numerator", names_transform = list(year = as.integer)) %>%
  mutate(areatype = "Council area",
         areaname = str_replace(areaname, "Edinburgh, City of","City of Edinburgh"),
         areaname = str_replace(areaname, "Orkney Isles","Orkney Islands"),
         areaname = str_replace(areaname, "Shetland","Shetland Islands"),
         areaname = str_replace(areaname, "Eilean Siar","Na h-Eileanan Siar"))  %>%
  select(areaname, areatype, year, numerator) %>%
  merge(y = geo_lookup, by=c("areaname", "areatype"), all.x=T)

# Combine LA data
register_la <- rbind(register_la_2007to2012, register_la_2013to2024) 
# Save ready for the main analysis function
saveRDS(register_la, file=paste0(profiles_data_folder, '/Prepared Data/child_prot_register_raw.rds'))

# Run main analysis function to aggregate and calculate rates (CA to higher geogs)
main_analysis(filename = "child_prot_register", ind_id = 13035, geography = "council", measure = "crude",
              pop = "CA_pop_under18_to2024", yearstart = 2007, yearend = 2024,
              time_agg = 1, crude_rate = 1000, year_type = "snapshot")

# Aggregated Scotland data match original Scotland data perfectly apart from 2015-2017, due to some suppression in smaller CAs. 

# Original Scotland data:
register_scot_main <- register_scot %>%
  filter(split_name=="Sex" & split_value=="All") %>%
  select(-starts_with("split"))

# Remove aggregated Scotland data and replace with the original data
main_analysis_result <- main_analysis_result %>%
  filter(code!="S00000001") %>%
  rbind(register_scot_main)

# Save
write_rds(main_analysis_result, paste0(profiles_data_folder, "/Data to be checked/child_prot_register_shiny.rds"))
write.csv(main_analysis_result, paste0(profiles_data_folder, "/Data to be checked/child_prot_register_shiny.csv"), row.names = FALSE)

# Run QA
run_qa(type = "main", filename = "child_prot_register", test_file = FALSE) 



########################################################################################
# CHILD PROTECTION CASES WITH CONCERNS RECORDED AS ALCOHOL/DRUGS/SUBSTANCE ABUSE
########################################################################################

# Import the data

# Scotland 2013-2024
concerns_scot_2013to2024 <- import_wide_data(filename = additional_2023, sheetnum = "1.2", range = "A5:M9", non_num_cols = c(1)) %>%
  pivot_longer(-(1), names_to = "year", values_to = "numerator", names_transform = list(year = as.integer)) %>%
  select(year, indicator = `Type of Concern`, numerator) 

# Scotland 2012 
concerns_scot_2012 <- import_wide_data(filename = additional_2014, sheetnum = "4.3", range = "A3:B7", non_num_cols = 1) %>%
  rename(indicator = ...1,
         `2012` = ...2) %>%
  pivot_longer(-indicator, names_to = "year", values_to = "numerator", names_transform = list(year = as.integer)) 

# Combine Scotland data, and calculate rates
concerns_scot <- rbind(concerns_scot_2012, concerns_scot_2013to2024) %>%
  mutate(ind_id = case_when(str_detect(indicator, "drug|Drug") ~ 4130,
                               str_detect(indicator, "alcohol|Alcohol") ~ 4110,
                               str_detect(indicator, "substance|Substance") ~ 4153,
                               TRUE ~ as.numeric(NA))) %>%
  filter(!is.na(ind_id)) %>%
  mutate(code = "S00000001",
         def_period = paste0(year, " - snapshot"), 
         trend_axis = as.character(year),
         split_name = "Total",
         split_value = "Total") %>%
  merge(y = pop_lookup_incl_2024, by=c("year", "code", "split_name", "split_value")) %>%
  calculate_crude_rate(., 10000) %>%
  select(-starts_with("split"), -denominator, -indicator)
  
  

# LA
concerns_la_count_2024 <- import_wide_LA_data(filename = additional_2023, sheetnum = "1.10", range = "A5:D37", year = "2024") 
concerns_la_count_2023 <- import_wide_LA_data(filename = additional_2022, sheetnum = "1.10", range = "A5:D37", year = "2023") 
concerns_la_count_2022 <- import_wide_LA_data(filename = additional_2021, sheetnum = "1.10", range = "A4:D36", year = "2022") 
concerns_la_count_2021 <- import_wide_LA_data(filename = additional_2020, sheetnum = "4.6", range = "A2:D34", year = "2021") 
concerns_la_count_2020 <- import_wide_LA_data(filename = additional_2019, sheetnum = "4.6", range = "A3:D35", year = "2020") 
concerns_la_count_2019 <- import_wide_LA_data(filename = additional_2018, sheetnum = "4.5", range = "A3:D35", year = "2019") 
concerns_la_count_2018 <- import_wide_LA_data(filename = additional_2017, sheetnum = "4.5", range = "A3:D35", year = "2018") 
concerns_la_count_2017 <- import_wide_LA_data(filename = additional_2016, sheetnum = "4.5", range = "A3:D35", year = "2017") 
concerns_la_count_2016 <- import_wide_LA_data(filename = additional_2015, sheetnum = "4.5", range = "A3:D35", year = "2016") 
concerns_la_count_2015 <- import_wide_LA_data(filename = additional_2014, sheetnum = "4.5", range = "A3:D35", year = "2015") 


concerns_la <- do.call("bind_rows", mget(ls(pattern="^concerns_la_"))) %>%
  mutate(ind_id = case_when(str_detect(indicator, "drug|Drug") ~ 4130,
                            str_detect(indicator, "alcohol|Alcohol") ~ 4110,
                            str_detect(indicator, "substance|Substance") ~ 4153,
                            TRUE ~ as.numeric(NA))) %>%
  filter(!is.na(ind_id))  %>%
  mutate(areaname = gsub(" and ", " & ", areaname)) %>%
  mutate(areaname = case_when(areaname == "Edinburgh, City of" ~ "City of Edinburgh",
                              areaname %in% c("Glasgow", "Glasgow City(7)") ~ "Glasgow City", 
                              areaname %in% c("Na hNAEileanan Siar", "Eilean Siar") ~ "Na h-Eileanan Siar",
                              TRUE ~ areaname)) %>%
  merge(y = geo_lookup, by=c("areaname", "areatype"), all.x=T) %>%
  select(-indicator, -areaname, -areatype)
# A fair number of zeroes in the data: these are true zeroes in small LAs
# Suppressed counts remain suppressed.

# Function to prepare main data file: 
prepare_main_data <- function(indicator, ind){
  
  main_data <- concerns_la %>% 
    filter(ind_id == ind) 
  
  # Save ready for the main analysis function
  saveRDS(main_data, file=paste0(profiles_data_folder, '/Prepared Data/', indicator, '_raw.rds'))

  # Run main analysis function to aggregate and calculate rates (CA to higher geogs)
  main_analysis(filename = indicator, ind_id = ind, geography = "council", measure = "crude",
                pop = "CA_pop_under18_to2024", yearstart = 2015, yearend = 2024,
                time_agg = 1, crude_rate = 10000, year_type = "snapshot", QA = FALSE)

  # Remove the aggregated Scotland data and replace with the original (because aggregated included some suppressed values)
  new_data <- main_analysis_result %>%
    filter(code!="S00000001") %>%
    rbind(concerns_scot) %>%
    filter(ind_id == ind) %>%
    arrange(code, year)
  
  # save 
  write_rds(new_data, paste0(profiles_data_folder, "/Data to be checked/", indicator, "_shiny.rds"))
  write.csv(new_data, paste0(profiles_data_folder, "/Data to be checked/", indicator, "_shiny.csv"), row.names = FALSE)
  
  # Run QA now:
  run_qa(type = "main", filename = indicator, test_file = FALSE) 
  
  # Make data created available outside of function so it can be visually inspected if required
  main_data_result <<- new_data
  
}


prepare_main_data(indicator = "child_protection_parental_drug", ind = 4130) 
prepare_main_data(indicator = "child_protection_parental_alcohol", ind = 4110) 
prepare_main_data(indicator = "child_protection_parental_substance_misuse" , ind = 4153) 
# zero rates found for island boards and some others, but these are based on true zeroes. 



# The rate differences for child_protection_all due to higher denominators now is understandable and to be expected.
# Other differences highlighted needed checking out. 
# Different numerators were found for some areas.
# The old and new data are compared below. This found that 84% of the comparisons were identical.
# The biggest difference was for Angus, 2021, current data says 45 on child protection register, tho the previous data said 25. 
# The raw data confirmed this. I would trust the latest data as more accurate (numbers may have been amended in the data source since the last update).
# Also the previous data was a spreadsheet that just got added to with the latest year's data, without making updates to any previous data that may have been corrected.
# In conclusion: I'm happy with the current data as is. 

# import older data for comparison:
ca <- readRDS(paste0(profiles_lookups,"/Geography/CAdictionary.rds")) %>%
  rename("ca"="code")

old_data <- read_excel("/PHI_conf/ScotPHO/Profiles/Data/Received Data/SG CYP Social Work stats/archive/CP CSWS 2012_22 revised 19_20.xlsx") %>%
  mutate(la = str_replace(la, "Glasgow","Glasgow City"),
         la = str_replace(la, "Edinburgh, City of","City of Edinburgh"),
         la = str_replace(la, "Eilean Siar","Na h-Eileanan Siar"),
         la = str_replace(la, "&","and"),
         across(contains(c("drug", "alcohol", "substance_misuse", "all")), as.numeric)) %>% #convert data columns to numeric (suppressed)
  left_join(ca, by = c("la" = "areaname")) %>% # join with council area lookup
  mutate(code = ifelse(la == "Scotland", "S00000001", ca)) %>%
  select(-ca) %>%
  pivot_longer(cols = c(drug, alcohol, substance_misuse, all_on_register), names_to = "indicator", values_to = "old_numerators") %>%
  mutate(indicator = case_when(indicator == "drug" ~ "child_protection_parental_drug", 
                               indicator == "alcohol" ~ "child_protection_parental_alcohol", 
                               indicator == "substance_misuse" ~ "child_protection_parental_substance_misuse", 
                               indicator == "all_on_register" ~ "child_protection_all"))

new_data <- all_data_scot_la %>%
  filter(split_value=="Total" & split_name == "Total") %>%
  mutate(year = as.numeric(trend_axis)) %>%
  select(year, code, indicator, numerator)

compare <- new_data %>%
  merge(y = old_data, by=c("year", "code", "indicator")) %>%
  mutate(diff_pc = 100 * (old_numerators - numerator) / old_numerators )
# 84% (833 of 996) have identical numerators. 


###END ----

