#  ScotPHO indicators: 2 indicator outputs from this script 
#  Female measures of life Expectancy inequality ,
#  Male measures of life expectancy inequality ,

# Inequalities measures for life expectancy require life expectancy data by SIMD quintile (generated by NRS) using equivalent time periods (eg 5 year average)
# Robust life expectancy estimate generation require sufficient data by individual year ages and sex and SIMD quintile this requires 5 years of data rather 
# than single year or 3 years data that is used in the main life expectancy profiles indicators

# Geographies available Scotland (Scotland Quintile), Council Area (using within Council SIMD quintile) and Health Board (within HB SIMD quinilte) 
# Within Scotland SIMD quintile estimates not available at CA or HB level as NRS do no routinely generate this data and unsure if the life expectancies would be robust given likely many categories where cells would be small/zeros

#   Part 1 - Import & manipulate raw data files provided by NRS.
#   Part 2 - Run analysis functions 

###############################################.
## Packages/Filepaths/Functions ----
###############################################.

source("1.indicator_analysis.R") #Normal indicator functions
source("2.deprivation_analysis.R") # deprivation function

# Extracts for Life Expectancy data saved in left expectancy network folder.
if (sessionInfo()$platform %in% c("x86_64-redhat-linux-gnu (64-bit)", "x86_64-pc-linux-gnu (64-bit)")) {
  source_network <- "/PHI_conf/ScotPHO/Life Expectancy/Data/Source Data/NRS data/"
} else {
  source_network <- "//stats/ScotPHO/Life Expectancy/Data/Source Data/NRS data/"
}

###############################################.
#   Small function to save final output files ----
###############################################.

save_output<-function(filename) {
  saveRDS(data_depr, paste0(data_folder, "Temporary/", filename, "_final.rds")) # not sure i really need this stage
  
  #Preparing data for Shiny tool
  data_shiny <- data_depr %>% 
    select(-c(most_rate, least_rate))
  
  #Saving file
  saveRDS(data_shiny, file = paste0(data_folder, "Data to be checked/", filename, "_ineq.rds"))
}

###############################################.
#   Part 1 - Import & manipulate raw data files provided by NRS. ----
###############################################.

#example of file end fields and structure 
example_ineq <- read_rds("/PHI_conf/ScotPHO/Profiles/Data/Shiny Data/deaths_allages_depr_ineq.rds")

# Mannually created Lookup for adding area standard geography codes to geography names.
area_lookup <- read_excel("/PHI_conf/ScotPHO/Life Expectancy/Data/Source Data/Area Lookup.xlsx")

# Open Health Board LE data
hb_depr_data <- read_excel(paste0(source_network,"life expectancy in health boards split by SIMD 2013-2017 to 2016-2020.xlsx")) %>%
  setNames(tolower(names(.))) %>%  #variables to lower case
  mutate(quint_type=case_when(substr(area,1,4) != "Scot" ~ "hb_quin",substr(area,1,4) == "Scot" ~"sc_quin")) #add field labelling quintile type - within HB quintile

# Open Health Board LE data (remove Scotland level data as already avialable in HB level data extract)
ca_depr_data <- read_excel(paste0(source_network,"life expectancy in council areas split by SIMD 2013-2017 to 2016-2020.xlsx")) %>%
  setNames(tolower(names(.))) %>% #variables to lower case
  subset(substr(area,1,4) != "Scot") %>% #remove scotland data from one dataset (already present in HB file)
  mutate(quint_type="ca_quin")

# Bind HB and CA data & rename fields
data_depr <- bind_rows(hb_depr_data,ca_depr_data) %>%
  filter(age_band=="less than 1") %>%
  rename(lowci= lower_le, upci=upper_le,rate=ex, denominator=populations, trend_axis=period) %>%
  mutate(quintile = substr(area, nchar(area)-1+1, nchar(area)),
         quintile = case_when(quintile=="0" ~ "Total", TRUE ~ quintile),
         area=substr(area,start=1,stop = nchar(area)-1),
         year=as.numeric(substr(trend_axis,1,4))+2) %>% #year field set to mid-point of time series - used in charting
  select(-lx,-age_band, -deaths)

#match on geography Standard geography codes
data_depr_all <- left_join(data_depr, area_lookup, by = c("area"))

rm(area_lookup,hb_depr_data,ca_depr_data)


##################################################.
##  Part 2 - Call deprivation analysis functions ----
##################################################.

##Female Life expectancy ----
data_depr <-data_depr_all %>%
  filter(sex=="F")

#call function to generate measures of inequality
inequality_measures()

#edit fields to match those required by profiles tool
data_depr_female <- data_depr %>%
  select(year, code, quintile, quint_type, denominator, rate, lowci,upci,sii:rel_range,trend_axis) %>%
  mutate(ind_id=20102,
         numerator = 0,
     def_period = paste0(trend_axis,"; ","5 year period life expectancy")) %>%
  # fill in missing values and if any have negative lower CI change that to zero.
  mutate_at(c("rate", "lowci", "upci"), ~replace(., is.na(.), 0)) 

 data_depr_female$lowci <- ifelse(data_depr_female$lowci<0, 0, data_depr_female$lowci)

 #call function to save file
 save_output(filename="life_expectancy_inequalities_female")


 ##Male Life expectancy ----
 data_depr <-data_depr_all %>%
   filter(sex=="M")
 
 #call function to generate measures of inequality
 inequality_measures()
 
 #edit fields to match those required by profiles tool
 data_depr_male <- data_depr %>%
   select(year, code, quintile, quint_type, denominator, rate, lowci,upci,sii:rel_range,trend_axis) %>%
   mutate(ind_id=20101,
          numerator = 0,
          def_period = paste0(trend_axis,"; ","5 year period life expectancy")) %>%
   # fill in missing values and if any have negative lower CI change that to zero.
   mutate_at(c("rate", "lowci", "upci"), ~replace(., is.na(.), 0)) 
 
 data_depr_male$lowci <- ifelse(data_depr_male$lowci<0, 0, data_depr_male$lowci)
 
#call function to save file
 save_output(filename="life_expectancy_inequalities_male")


 
##################################################.
##  Part 3 - Checkign charts ----
# New indicators which work in opposite direction to most inequalities indicators just creating 
# some charts to test how data works
##################################################. 
 
####Charting rate by quintile ----
 
chart <- data_depr_male %>%
filter(code=="S00000001" & quintile !="Total")

 p <- plot_ly(data=chart , x=~trend_axis) %>%
   #Comparator line
   add_lines(y = ~rate, name = "Life Ex", type = 'scatter', mode = 'lines',
             color=~quintile, text= ~quintile, hoverinfo="text") %>%
   layout(bargap = 0.1, margin=list(b = 140), #to avoid labels getting cut out
          showlegend = FALSE) %>%
   config(displayModeBar = F, displaylogo = F, editable =F) # taking out toolbar

 p
 

####Charting sii ----

chart2 <- data_depr_male %>%
  filter(code=="S00000001" & quintile =="Total")

sii_plot <- plot_ly(data=chart2, x=~trend_axis,hoverinfo="text") %>%
  add_lines(y = ~sii, name = "Absolute inequality (SII)", type = 'scatter', mode = 'lines',
            line = list(color = '#74add1'))  %>% 
  #Layout
  layout(showlegend = FALSE,
         margin = list(b = 140)) %>% 
  config(displayModeBar = FALSE, displaylogo = F,  editable =F) # taking out toolbar

sii_plot

####Charting rii ----

rii_plot <- plot_ly(data=chart2, x=~trend_axis)%>%
  add_lines(y = ~rii,name = "Relative gap", type = 'scatter', mode = 'lines',
            line = list(color = '#313695')) %>% 
  #Layout
  layout(showlegend = FALSE, margin = list(b = 140))%>%
  config(displayModeBar = FALSE, displaylogo = F, editable =F) # taking out toolbar

rii_plot

####Charting paf ----

#preparing data needed, creates two dummy variables for stacked bar chart
chart3<- data_depr_male %>%
  filter(code=="S00000001" & year=="2018" & quintile !="Total") %>%
  mutate(baseline = rate[quintile == "5"],
         diff_baseline = rate - rate[quintile == "5"]) %>% 
  droplevels()

par_bar_plot <- plot_ly(data = chart3, x = ~quintile, 
                        textposition="none", hoverinfo="text") %>%
  add_bars(y = ~baseline, name= "", marker = list(color = "#4da6ff"), showlegend = FALSE) %>%   
  add_bars(y = ~diff_baseline, name = "Attributable to deprivation", 
           marker = list(color = "#ffa64d"), showlegend = FALSE) %>% 
  layout(bargap = 0.1, barmode = 'stack', showlegend = T, 
         legend = list(x = 0.9, y = 0.9),
         margin = list(b = 140)) %>% #to avoid labels getting cut out
  config(displayModeBar = FALSE, displaylogo = F, editable =F) # taking out toolbar

par_bar_plot 