################################################################################
################################################################################
#########                                                              #########
#####               Recorded crime profile indicators prep                 #####
#########                                                              #########
################################################################################
################################################################################

## This script prepares SG recorded crime profile indicators:

##      Common assault
##      Drug crimes recorded
##      Vandalism
##      Violent crime
##      Attempted murder & serious assault 
##      Breach of the Peace  (currently unincluded due to changes in crime categorisations by stats.gov)

## Data are automatically downloaded from statistics.scot.gov.uk using the opendata package:
# install the opendata scotland r package which communicates with the statistics.gov wesbite api
# install.packages("devtools")
# devtools::install_github("datasciencescotland/opendatascot")

source("1.indicator_analysis.R")
library(opendatascot)

# indicator name is one of the names in the crimes list inside the function
# start year is year to start extraction
# end_year is most recent year for which data is available 
# most recent year available can be seen by running line below and looking at $categories$refPeriod
# Note: years in ods structure result below represent financial years e.g 2022  is for 2021/2022 , 2021 is for 2020/21
ods_structure("recorded-crime") # see structure and variables contained in the recorded-crimes dataset
# to update the data set the year in the extract data function calls in lines 76-80, to the most recent year 

# creating function to extract crime indicators 
extract_crime = function(indicator_name,start_year,end_year){
  
  # URI= names of data in stats.gov opendata 
  # filename= name of file in shiny data folders
  # id= indicator id number
  crimes = list(common_assault = list("URI"="crimes-group-1-common-assault","filename"="4154_commonassault","id"=4154),
                vandalism = list("URI"="crimes-group-4-vandalism","filename"="4155_vandalism","id"=4155),
                serious_assault = list("URI"="crimes-group-1-serious-assault-and-attempted-murder","filename"="4111_murderseriousassault","id"=4111),
                drug_crimes = list("URI"=NULL,"filename"="20806_drugs","id"=20806),
                violent_crime = list("URI"="all-group-1-non-sexual-crimes-of-violence","filename"="20805_violentcrime","id"=20805))
  
  date_range = (as.character(start_year:end_year))
  
  if (indicator_name!="drug_crimes") { # for indicator crime which isn't drug crimes
    crime_data = ods_dataset("recorded-crime",geography = "la", refPeriod=date_range,
                             crimeOrOffence= crimes[[indicator_name]]$URI, measureType="count") %>%  
      setNames(tolower(names(.))) %>%
      select("ca"= "refarea","year"="refperiod","numerator"="value") %>%
      mutate(year=substr(year,1,4)) %>%
      mutate(across(c("numerator","year"), ~ as.numeric(.))) 
  }
  else { # for drug crimes which is a combination of extractions from two different datasets
    crime_data = rbind( 
      
      ods_dataset("recorded-crime",geography = "la", refPeriod=date_range,
                  crimeOrOffence="crimes-group-5-drugs-possession",measureType="count") %>%  
        setNames(tolower(names(.))) %>%
        select("ca"= "refarea","year"="refperiod","numerator"="value") %>%
        mutate(year=substr(year,1,4)) %>%
        mutate(across(c("numerator","year"), ~ as.numeric(.))),
      
      ods_dataset("recorded-crime",geography = "la", refPeriod=date_range,
                  crimeOrOffence="crimes-group-5-drugs-supply",measureType="count") %>%  
        setNames(tolower(names(.))) %>%
        select("ca"= "refarea","year"="refperiod","numerator"="value") %>%
        mutate(year=substr(year,1,4)) %>%
        mutate(across(c("numerator","year"), ~ as.numeric(.)))
      
    ) %>% 
      group_by(ca,year) %>% 
      summarise(numerator = sum(numerator))
    
  }
  
  saveRDS(crime_data, file=paste0(data_folder, 'Prepared Data/',crimes[[indicator_name]]$filename,'_raw.rds')) 
  
  analyze_first(filename = crimes[[indicator_name]]$filename, geography = "council", measure = "crude", yearstart = start_year,
                yearend = end_year, time_agg = 1, adp = TRUE, pop = "CA_pop_allages")
  
  analyze_second(filename = crimes[[indicator_name]]$filename, measure = "crude", time_agg = 1,
                 ind_id = crimes[[indicator_name]]$id, year_type = "financial",crude_rate = 10000) 
  
}


# run function for each crime indicator extract
# visualise the quality checks generated by the analyse_second QA output before 
# kill the terminal and run next line for next crime indicator
extract_crime("common_assault",2004,2022) 
extract_crime("vandalism",2004,2022)
extract_crime("serious_assault",2004,2022)
extract_crime("drug_crimes",2004,2022)
extract_crime("violent_crime",2004,2022)

# END
